name: lab02
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: echo Hello
      - run: pip install nbconvert
      - run: python -m nbconvert --to pdf pint_and_boiling_point.ipynb