name: Lab 05
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install inkscape pandoc texlive-xetex
      - run: pip install nbconvert ipykernel pint matplotlib scipy open_atmos_jupyter_utils
      - run: python -m nbconvert --to pdf --execute lab05.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: lab05.pdf