name: lab02
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install inkscape pandoc texlive-xetex
      - run: pip install nbconvert ipykernel
      - run: python -m nbconvert --to pdf pint_and_boiling_point.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: pint_and_boiling_point.pdf